import { StyleSheet } from 'react-native';
import { type ColorScheme, Typography, Spacing, Radius } from '../../theme';

export const makeStyles = (c: ColorScheme) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: c.background },
  container: { padding: Spacing.md, paddingBottom: Spacing.xxl },
  heroCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: c.border,
    padding: Spacing.md,
    marginBottom: Spacing.md,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginBottom: 4,
  },
  heroTitle: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
  },
  heroSub: {
    fontSize: Typography.size.sm,
    color: c.textSecondary,
    lineHeight: 20,
  },
  sermonTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.lg,
  },
  sermonNew: {
    fontSize: Typography.size.xl,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
  },
  clearBtn: {
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
  },
  clearText: { fontSize: Typography.size.sm, color: c.textSecondary },
  fieldLabel: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
    letterSpacing: 1.2,
    marginBottom: Spacing.xs,
    marginTop: Spacing.sm,
  },
  metaCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginBottom: Spacing.md,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: Spacing.sm,
    gap: Spacing.sm,
  },
  metaTextWrap: {
    flex: 1,
  },
  metaLabel: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    letterSpacing: 1,
    marginBottom: 2,
  },
  metaInput: {
    marginBottom: 0,
    width: '100%',
  },
  metaValue: { fontSize: Typography.size.md, color: c.textPrimary },
  dividerLine: { height: 1, backgroundColor: c.border },
  notesToolsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: Spacing.xs,
    marginBottom: Spacing.sm,
  },
  toolBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    backgroundColor: c.surface,
  },
  toolBtnText: {
    fontSize: Typography.size.xs,
    color: c.textSecondary,
    fontWeight: Typography.weight.medium,
  },
  notesBox: {
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: Radius.md,
    backgroundColor: c.surface,
    minHeight: 220,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    marginBottom: Spacing.md,
  },
  notesInput: {
    color: c.textPrimary,
    minHeight: 190,
    lineHeight: 24,
  },
  charCount: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    textAlign: 'right',
    marginTop: -Spacing.xs,
    marginBottom: Spacing.md,
    letterSpacing: 1,
  },
  photoRow: {
    gap: Spacing.sm,
    paddingBottom: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  photoItem: {
    width: 96,
    height: 96,
    borderRadius: Radius.md,
    overflow: 'hidden',
    backgroundColor: c.surfaceAlt,
  },
  photoThumb: {
    width: '100%',
    height: '100%',
  },
  photoRemoveBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  photoReorderRow: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    flexDirection: 'row',
    gap: 6,
  },
  photoControlBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  customTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    marginBottom: Spacing.lg,
  },
  customTagInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: Radius.md,
    backgroundColor: c.surface,
    color: c.textPrimary,
    paddingHorizontal: Spacing.md,
  },
  customTagBtn: {
    alignSelf: 'center',
    borderWidth: 1.5,
    borderColor: c.border,
    borderRadius: Radius.md,
    borderStyle: 'dashed',
    paddingHorizontal: Spacing.md,
    paddingVertical: 9,
  },
  customTagText: { fontSize: Typography.size.sm, color: c.textSecondary },
  customTagsManageWrap: {
    marginTop: -Spacing.sm,
    marginBottom: Spacing.lg,
  },
  customTagsManageTitle: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    fontWeight: Typography.weight.bold,
    letterSpacing: 1,
    marginBottom: Spacing.xs,
  },
  customTagsManageRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.xs,
  },
  customTagPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surface,
    paddingLeft: Spacing.sm,
    paddingRight: 6,
    paddingVertical: 4,
  },
  customTagPillText: {
    fontSize: Typography.size.xs,
    color: c.textSecondary,
    fontWeight: Typography.weight.medium,
  },
  customTagDeleteBtn: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  requirementsCard: {
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surface,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginBottom: Spacing.lg,
    gap: Spacing.xs,
  },
  requirementsTitle: {
    fontSize: Typography.size.xs,
    letterSpacing: 1,
    color: c.textMuted,
    fontWeight: Typography.weight.bold,
    marginBottom: 2,
  },
  requirementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  requirementText: {
    fontSize: Typography.size.sm,
    color: c.textSecondary,
  },
  requirementTextError: {
    color: c.error,
  },
  saveBtn: { width: '100%' },
  exportWrap: {
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: c.border,
  },
  exportRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    marginBottom: Spacing.sm,
  },
  exportBtn: {
    flex: 1,
    height: 42,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
  },
  exportBtnText: {
    fontSize: Typography.size.sm,
    fontWeight: Typography.weight.semiBold,
    color: c.textSecondary,
  },
  fullscreenOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.md,
  },
  fullscreenClose: {
    position: 'absolute',
    top: 52,
    right: 20,
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
    zIndex: 10,
  },
  fullscreenImage: {
    width: '100%',
    height: '82%',
  },
}
);