import { StyleSheet } from 'react-native';
import { Colors, Typography, Spacing, Radius } from '../../theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  backBtn: { width: 40, padding: Spacing.xs },
  headerTitle: {
    fontSize: Typography.size.lg,
    fontWeight: Typography.weight.semiBold,
    color: Colors.textPrimary,
  },
  headerSpacer: { width: 40 },
  container: {
    padding: Spacing.lg,
    paddingBottom: Spacing.xxl,
    alignItems: 'center',
  },
  iconWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: Colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.lg,
    marginTop: Spacing.md,
  },
  title: {
    fontSize: Typography.size.xl,
    fontWeight: Typography.weight.bold,
    color: Colors.textPrimary,
    textAlign: 'center',
    marginBottom: Spacing.sm,
  },
  subtitle: {
    fontSize: Typography.size.md,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: Spacing.lg,
  },
  fieldLabel: {
    alignSelf: 'flex-start',
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: Colors.textMuted,
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  inputFull: { alignSelf: 'stretch' },
  sentBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F1F12',
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginTop: Spacing.sm,
    alignSelf: 'stretch',
  },
  sentText: { fontSize: Typography.size.sm, color: Colors.success, flex: 1 },
  sendBtn: { alignSelf: 'stretch', marginTop: Spacing.md },
  tipCard: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    backgroundColor: Colors.surfaceAlt,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginTop: Spacing.lg,
  },
  tipText: {
    flex: 1,
    fontSize: Typography.size.sm,
    color: Colors.textSecondary,
    lineHeight: 20,
  },
  backLink: { marginTop: Spacing.lg },
  backLinkText: {
    fontSize: Typography.size.md,
    color: Colors.primary,
    fontWeight: Typography.weight.semiBold,
  },
  helpLink: { marginTop: Spacing.sm },
  helpText: { fontSize: Typography.size.sm, color: Colors.textMuted },
}
);