import { StyleSheet } from 'react-native';
import { type ColorScheme, Typography, Spacing, Radius } from '../../theme';

export const makeStyles = (c: ColorScheme) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: c.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: c.border,
    backgroundColor: c.surface,
  },
  headerTitle: {
    fontSize: Typography.size.lg,
    fontWeight: Typography.weight.semiBold,
    color: c.textPrimary,
  },
  container: { padding: Spacing.lg, paddingBottom: Spacing.xxl, alignItems: 'center' },
  avatarWrap: { position: 'relative', marginBottom: Spacing.md, marginTop: Spacing.md },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: c.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: c.border,
  },
  avatarInitials: {
    fontSize: Typography.size.xxl,
    fontWeight: Typography.weight.bold,
    color: c.primary,
  },
  editBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: c.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: c.border,
  },
  name: {
    fontSize: Typography.size.xl,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
    marginBottom: Spacing.xs,
  },
  memberSince: {
    fontSize: Typography.size.sm,
    color: c.accent,
    marginBottom: Spacing.md,
  },
  levelText: {
    fontSize: Typography.size.sm,
    color: c.textSecondary,
    fontWeight: Typography.weight.medium,
    marginBottom: Spacing.lg,
  },
  statsRow: {
    flexDirection: 'row',
    gap: Spacing.md,
    width: '100%',
    marginBottom: Spacing.lg,
  },
  statCard: {
    flex: 1,
    backgroundColor: c.surface,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  statNum: {
    fontSize: Typography.size.xxl,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
  },
  statLabel: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    letterSpacing: 1,
    marginTop: 2,
  },
  statSub: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    marginTop: 2,
  },
  sectionLabel: {
    alignSelf: 'flex-start',
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
    letterSpacing: 1.5,
    marginBottom: Spacing.sm,
    marginTop: Spacing.md,
  },
  card: {
    backgroundColor: c.surface,
    borderRadius: Radius.lg,
    paddingHorizontal: Spacing.md,
    width: '100%',
    marginBottom: Spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  lastRow: { borderBottomWidth: 0 },
  toggleOff: {
    width: 44,
    height: 26,
    borderRadius: 13,
    backgroundColor: c.border,
  },
  signOutRow: {},
  version: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    letterSpacing: 1,
    marginTop: Spacing.lg,
  },
}
);