import { StyleSheet } from 'react-native';
import { type ColorScheme, Typography, Spacing, Radius } from '../../theme';

export const makeStyles = (c: ColorScheme) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: c.background },
  container: { padding: Spacing.md, paddingBottom: Spacing.xxl },
  metaBadge: {
    alignSelf: 'flex-start',
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    marginBottom: Spacing.sm,
  },
  metaBadgeText: {
    fontSize: Typography.size.xs,
    color: c.primary,
    fontWeight: Typography.weight.semiBold,
  },
  pageTitle: {
    fontSize: Typography.size.xl,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
    marginBottom: 4,
  },
  pageDate: {
    fontSize: Typography.size.sm,
    color: c.textMuted,
    marginBottom: Spacing.lg,
  },
  sectionCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: c.border,
  },
  sectionActive: {},
  sectionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  letterBox: {
    width: 36,
    height: 36,
    borderRadius: Radius.sm,
    backgroundColor: c.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.sm,
  },
  letter: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.bold,
    color: '#10B981',
  },
  sectionInfo: { flex: 1 },
  sectionTitle: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
  },
  sectionHint: { fontSize: Typography.size.sm, color: c.textSecondary },
  subLabel: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
    letterSpacing: 1.2,
    marginBottom: Spacing.xs,
  },
  charCount: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    textAlign: 'right',
    marginTop: -Spacing.sm,
    marginBottom: Spacing.xs,
  },
  proTip: {
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginBottom: Spacing.lg,
  },
  proTipLabel: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: '#10B981',
    letterSpacing: 1,
    marginBottom: Spacing.xs,
  },
  proTipText: {
    fontSize: Typography.size.sm,
    color: c.textSecondary,
    lineHeight: Typography.size.sm * 1.5,
  },
  saveBtn: { width: '100%' },
  savedHint: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    textAlign: 'center',
    marginTop: Spacing.sm,
  },
});
