import { StyleSheet } from 'react-native';
import { type ColorScheme, Typography, Spacing, Radius } from '../../theme';

export const makeStyles = (c: ColorScheme) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: c.background },

  // Consistency
  consistencyPanel: {
    backgroundColor: c.surface,
    padding: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: c.border,
  },
  consistencyTitle: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
    letterSpacing: 1.5,
    marginBottom: Spacing.sm,
  },
  statsRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  statBadge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    gap: Spacing.sm,
  },
  statBadgeValue: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
  },
  statBadgeLabel: {
    fontSize: 9,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
    letterSpacing: 0.5,
  },
  streakEmoji: {
    fontSize: 24,
  },

  // Day grid
  dayGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayItem: { alignItems: 'center', flex: 1 },
  dayChar: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
    marginBottom: 4,
  },
  dayDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: c.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: c.border,
  },
  dayDotDone: { backgroundColor: c.primary, borderColor: c.primary },
  dayDotToday: { borderColor: c.primary, borderWidth: 2 },
  // Entries
  entriesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.md,
    paddingBottom: 4,
  },
  sectionLabel: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
    letterSpacing: 1.5,
  },
  entryCount: { fontSize: Typography.size.sm, color: c.textMuted },

  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: Radius.lg,
    marginHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
    paddingHorizontal: Spacing.md,
    height: 44,
    borderWidth: 1,
    borderColor: c.border,
  },
  searchInput: { flex: 1, fontSize: Typography.size.md, color: c.textPrimary },

  list: { padding: Spacing.md, paddingBottom: Spacing.xxl },

  entryCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  entryMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  entryMetaRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  deleteBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.surfaceAlt,
  },
  entryDate: { fontSize: Typography.size.xs, color: c.textMuted },
  typeBadge: {
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
  },
  typeText: {
    fontSize: 10,
    fontWeight: Typography.weight.bold,
    color: '#fff',
    letterSpacing: 0.5,
  },
  entryTitle: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.semiBold,
    color: c.textPrimary,
    marginBottom: 4,
  },
  entryExcerpt: {
    fontSize: Typography.size.sm,
    color: c.textSecondary,
    lineHeight: 20,
    marginBottom: Spacing.sm,
  },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  tag: {
    backgroundColor: c.surfaceAlt,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
  },
  tagText: { fontSize: 10, color: c.textMuted, fontWeight: Typography.weight.medium },

  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: Spacing.xl },
  emptyTitle: {
    fontSize: Typography.size.xl,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
    marginBottom: Spacing.sm,
  },
  emptySubtitle: { fontSize: Typography.size.md, color: c.textSecondary, textAlign: 'center' },
  typeFilterScroll: {
    flexGrow: 0,
    backgroundColor: c.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.border,
  },
  typeFilterRow: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    gap: Spacing.sm,
    alignItems: 'center',
  },
  typeChip: {
    height: 36,
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.full,
    borderWidth: 1.5,
    borderColor: c.border,
    backgroundColor: c.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 52,
  },
  typeChipActive: {
    backgroundColor: c.primary,
    borderColor: c.primary,
  },
  typeChipText: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textSecondary,
    letterSpacing: 0.5,
  },
  typeChipTextActive: {
    color: c.textOnPrimary,
  },

  dateRangeWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    backgroundColor: c.surface,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.border,
  },
  datePickerBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 36,
    paddingHorizontal: Spacing.sm,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surfaceAlt,
  },
  datePickerLabel: {
    fontSize: 11,
    fontWeight: Typography.weight.bold,
    color: c.textSecondary,
    letterSpacing: 0.4,
  },
  clearDateBtn: {
    marginLeft: 'auto',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    borderRadius: Radius.md,
    backgroundColor: c.surfaceAlt,
    borderWidth: 1,
    borderColor: c.border,
  },
  clearDateText: {
    fontSize: 11,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
  },
  recentSearchScroll: {
    flexGrow: 0,
    marginBottom: Spacing.xs,
  },
  recentSearchRow: {
    flexDirection: 'row',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.xs,
  },
  recentSearchChip: {
    height: 28,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surfaceAlt,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
  },
  recentSearchText: {
    fontSize: Typography.size.xs,
    color: c.textSecondary,
  },
  dateStatusText: {
    fontSize: Typography.size.xs,
    color: c.textSecondary,
    paddingHorizontal: Spacing.md,
    paddingTop: 6,
    paddingBottom: 2,
  },
  calendarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.md,
  },
  calendarCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: Radius.lg,
    backgroundColor: c.surface,
    padding: Spacing.md,
  },
  calendarHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.xs,
  },
  calendarNavBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: c.surfaceAlt,
  },
  calendarTitle: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.bold,
    color: c.textPrimary,
  },
  calendarHint: {
    fontSize: Typography.size.xs,
    color: c.textMuted,
    marginBottom: Spacing.sm,
    textAlign: 'center',
  },
  calendarWeekHeader: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  calendarWeekDay: {
    flex: 1,
    textAlign: 'center',
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  calendarCell: {
    width: '13.6%',
    aspectRatio: 1,
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarCellHasEntry: {
    backgroundColor: c.primary + '1A',
  },
  calendarCellSelected: {
    backgroundColor: c.primary,
  },
  calendarCellText: {
    fontSize: Typography.size.sm,
    color: c.textPrimary,
    fontWeight: Typography.weight.medium,
  },
  calendarCellTextSelected: {
    color: c.textOnPrimary,
    fontWeight: Typography.weight.bold,
  },
  calendarEntryDot: {
    position: 'absolute',
    bottom: 5,
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: c.primary,
  },
  calendarActions: {
    marginTop: Spacing.md,
    alignItems: 'flex-end',
  },
  calendarActionBtn: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    borderRadius: Radius.md,
    backgroundColor: c.surfaceAlt,
  },
  calendarActionText: {
    fontSize: Typography.size.sm,
    fontWeight: Typography.weight.bold,
    color: c.textSecondary,
  },

  /* ─── multi-select ─── */
  entriesHeaderRight: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  selectBtn: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 4,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: c.primary,
  },
  selectBtnText: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.primary,
    letterSpacing: 0.5,
  },
  selectBtnCancel: { borderColor: c.error },
  selectBtnCancelText: { color: c.error },
  entryCardSelected: { borderWidth: 1.5, borderColor: c.primary },
  checkCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: c.border,
    marginRight: Spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkCircleSelected: { borderColor: c.primary, backgroundColor: c.primary },
  bottomSelectBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: c.surface,
    borderTopWidth: 1,
    borderTopColor: c.border,
    padding: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: Spacing.lg,
  },
  selectCount: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.semiBold,
    color: c.textSecondary,
  },
  bulkDeleteBtn: {
    borderRadius: Radius.md,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.lg,
    backgroundColor: c.error,
    flexDirection: 'row',
    gap: Spacing.xs,
    alignItems: 'center',
  },
  bulkDeleteText: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.bold,
    color: '#fff',
  },
}
);