import { StyleSheet } from 'react-native';
import { type ColorScheme, Typography, Spacing, Radius } from '../../theme';

export const makeStyles = (c: ColorScheme) => StyleSheet.create({
  safe:    { flex: 1, backgroundColor: c.background },
  scroll:  { flex: 1 },
  content: { paddingBottom: Spacing.xxl },

  // ─── Hero ───────────────────────────────────────────────────────────────────
  heroWrap: { padding: Spacing.md },
  heroCap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  heroDateCol: {},
  heroDayLabel: { fontSize: Typography.size.xs, fontWeight: Typography.weight.bold, color: c.primary, letterSpacing: 1.5 },
  heroDate: { fontSize: Typography.size.sm, color: c.textMuted, marginTop: 1 },

  themeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: Radius.full,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
  },
  themeBadgeText: { fontSize: Typography.size.xs, color: c.textSecondary, fontWeight: Typography.weight.medium },

  // Main verse card
  verseCard: {
    backgroundColor: c.surface,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    marginBottom: Spacing.sm,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
  },
  quoteDecor: {
    fontSize: 48,
    lineHeight: 40,
    color: c.primary,
    opacity: 0.25,
    fontFamily: Typography.fontFamilySerif,
    marginBottom: 4,
  },
  verseText: {
    fontSize: Typography.size.lg,
    color: c.textPrimary,
    lineHeight: 30,
    fontFamily: Typography.fontFamilySerif,
    fontStyle: 'italic',
    marginBottom: Spacing.md,
  },
  verseRefRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  verseRef: {
    fontSize: Typography.size.sm,
    fontWeight: Typography.weight.bold,
    color: c.primary,
    letterSpacing: 0.5,
  },

  // ─── Action buttons ─────────────────────────────────────────────────────────
  actionRow: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.md },
  actionBtn: {
    flex: 1,
    height: 46,
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: Spacing.xs,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
  },
  actionBtnPrimary: { backgroundColor: c.primary, borderColor: c.primary },
  actionBtnText: { fontSize: Typography.size.sm, fontWeight: Typography.weight.semiBold, color: c.textSecondary },
  actionBtnTextPrimary: { color: c.textOnPrimary },

  // ─── Notification banner ─────────────────────────────────────────────────────
  notifBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.surface,
    borderRadius: Radius.md,
    marginHorizontal: Spacing.md,
    marginBottom: Spacing.md,
    padding: Spacing.md,
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: c.border,
  },
  notifIconWrap: {
    width: 38,
    height: 38,
    borderRadius: Radius.md,
    backgroundColor: c.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifText:  { flex: 1 },
  notifTitle: { fontSize: Typography.size.sm, fontWeight: Typography.weight.semiBold, color: c.textPrimary },
  notifSub:   { fontSize: Typography.size.xs, color: c.textMuted, marginTop: 1 },

  // ─── Upcoming verses list ────────────────────────────────────────────────────
  sectionLabel: {
    fontSize: Typography.size.xs,
    fontWeight: Typography.weight.bold,
    color: c.textMuted,
    letterSpacing: 1.5,
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
  },
  miniCard: {
    flexDirection: 'row',
    backgroundColor: c.surface,
    borderRadius: Radius.md,
    marginHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
    overflow: 'hidden',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
  },
  miniAccent: { width: 4 },
  miniBody:   { flex: 1, padding: Spacing.md },
  miniDay:    { fontSize: Typography.size.xs, color: c.textMuted, marginBottom: 3 },
  miniVerse:  { fontSize: Typography.size.sm, color: c.textPrimary, lineHeight: 20, marginBottom: 4 },
  miniRef:    { fontSize: Typography.size.xs, fontWeight: Typography.weight.bold, color: c.primary },
  miniTheme:  {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Radius.full,
    backgroundColor: c.surfaceAlt,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  miniThemeText: { fontSize: 9, color: c.textMuted, fontWeight: Typography.weight.medium, letterSpacing: 0.5 },
});
