import { StyleSheet } from 'react-native';
import { Colors, Typography, Spacing, Radius } from '../../theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  headerTitle: {
    fontSize: Typography.size.lg,
    fontWeight: Typography.weight.bold,
    color: Colors.textPrimary,
  },
  searchBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },

  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  searchInput: { flex: 1, fontSize: Typography.size.md, color: Colors.textPrimary },

  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  selector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceAlt,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    marginRight: 4,
  },
  selectorBook: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.semiBold,
    color: Colors.primary,
    marginRight: 4,
  },
  selectorChapter: {
    fontSize: Typography.size.md,
    fontWeight: Typography.weight.semiBold,
    color: Colors.primary,
    marginRight: 4,
  },
  navButtons: { flexDirection: 'row', marginLeft: 'auto', gap: 4 },
  navBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdown: {
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 100,
  },
  dropItem: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  dropItemActive: { backgroundColor: Colors.surfaceAlt },
  dropText: { fontSize: Typography.size.md, color: Colors.textPrimary },
  dropTextActive: { color: Colors.primary, fontWeight: Typography.weight.semiBold },
  chapterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: Spacing.sm,
    gap: 6,
  },
  chapterDot: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chapterDotActive: { backgroundColor: Colors.primary },
  chapterDotText: { fontSize: Typography.size.md, color: Colors.textPrimary },
  chapterDotTextActive: { color: '#fff', fontWeight: Typography.weight.bold },

  verseList: { flex: 1 },
  verseListContent: { padding: Spacing.md, paddingBottom: Spacing.xxl },
  chapterHeading: {
    fontSize: Typography.size.display,
    fontWeight: Typography.weight.bold,
    color: Colors.primary,
    marginBottom: Spacing.md,
  },
  verseRow: {
    flexDirection: 'row',
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.xs,
    borderRadius: Radius.sm,
    marginBottom: 2,
  },
  verseRowSelected: { backgroundColor: '#2A1F10' },
  verseNum: {
    width: 28,
    fontSize: Typography.size.sm,
    fontWeight: Typography.weight.bold,
    color: Colors.accent,
    paddingTop: 2,
  },
  verseText: {
    flex: 1,
    fontSize: Typography.size.md,
    color: Colors.textPrimary,
    lineHeight: 24,
  },
  verseTextSelected: { color: Colors.primary },

  hintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceAlt,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginTop: Spacing.lg,
  },
  hintText: { flex: 1, fontSize: Typography.size.sm, color: Colors.textSecondary },

  actionBar: {
    flexDirection: 'row',
    backgroundColor: Colors.primary,
    paddingVertical: Spacing.sm,
  },
  actionBtn: { flex: 1, alignItems: 'center', paddingVertical: Spacing.xs },
  actionText: {
    fontSize: 9,
    color: '#fff',
    fontWeight: Typography.weight.bold,
    letterSpacing: 0.5,
  },
}
);